#server:
#  port: 9098    #port number
#
#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:8761/eureka/
#    healthcheck:
#      enabled: true
#    lease:
#      duration: 5
#
#spring:
#  application:
#    name: track-service    #service name
#
#  data:
#    mongodb:
#      repositories:
#        enabled: true
#
#      host: localhost
#
#  driverClassName: com.mongodb.jdbc.MongoDriver
#
#logging:
#  level:
#    com.stackrout.route: DEBUG